FROM openjdk:16-jdk-buster

RUN mkdir /opt/tomcat/

WORKDIR /opt/tomcat

RUN curl -O https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.12/bin/apache-tomcat-10.0.12.tar.gz

RUN tar xvfz apache*.tar.gz

RUN mv apache-tomcat-10.0.12/* /opt/tomcat/.

WORKDIR /opt/tomcat/webapps

COPY webapps/CoWinRdServer.war .

EXPOSE 8080

CMD ["/opt/tomcat/bin/catalina.sh", "run"]